import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/app/generated/prisma/client";

/**
 * One Prisma client per request.
 *
 * The obvious implementation caches the client on `globalThis`, and that is
 * what this file used to do. On Cloudflare Workers it hangs: the first request
 * succeeds and every request after it never returns, with no exception to
 * catch and no stack pointing anywhere near Prisma. Reproduced against
 * workerd on 2026-08-24; see docs/architecture/SPIKE-RESULTS.md and
 * prisma/prisma#28193. Nothing here may cache a client on `globalThis`.
 *
 * A Worker isolate serves many requests, so "module scope" is not "per
 * request" the way it is under `next dev`. Two different request boundaries
 * exist, because the two Workers are built differently:
 *
 * - The engine is a raw wrangler Worker whose entrypoint we own, so it wraps
 *   each cron tick and queue batch in `withPrismaScope` and the client lives in
 *   an `AsyncLocalStorage` store it can also close afterwards.
 * - The web Worker's entrypoint is generated by OpenNext, which wraps requests
 *   in its own `runWithCloudflareRequestContext` and gives no seam to add ours.
 *   `withPrismaScope` is therefore never called there. That used to mean every
 *   `prisma.<model>` expression built a fresh client, pool and TCP socket:
 *   ~23 of them for one `/api/dashboard/stats` request, against a Hyperdrive
 *   `origin_connection_limit` of 20, so the route was throttling itself on
 *   connections it had just opened and never closed.
 *
 * What the web Worker does have is the adapter's per-invocation context. The
 * `ExecutionContext` inside it is allocated per request by the runtime, so a
 * `WeakMap` keyed on it is a per-request cache with no global state and no
 * lifetime to manage: the entry becomes collectable with the request itself.
 *
 * Outside both (scripts, tests, plain `next dev` with no adapter context) there
 * is no boundary to hang state on, so a client is created on demand and the
 * caller owns closing it.
 */
import { AsyncLocalStorage } from "node:async_hooks";
import { getCloudflareContextOrNull, tryBindings } from "@/lib/cloudflare/bindings";

const requestScope = new AsyncLocalStorage<{ client?: PrismaClient }>();

/**
 * Keyed on the adapter's `ExecutionContext`, which is per invocation. Weak so a
 * finished request's client is not reachable from module scope, which is the
 * thing prisma/prisma#28193 punishes.
 */
const clientsByExecutionContext = new WeakMap<object, PrismaClient>();

/**
 * Where to connect, and it matters which one wins.
 *
 * Hyperdrive hands back a local address the Workers socket layer permits. A
 * Worker dialling the origin itself is blocked outright when that origin is a
 * private IP, which is what happens behind Azure Private Link: the socket layer
 * refuses with "cannot connect to the specified address" and no amount of
 * tunnel or route configuration changes it.
 *
 * This read the secret directly and never touched the binding, so Hyperdrive
 * was never in the query path at all. That went unnoticed because a publicly
 * reachable database works fine either way, and it only surfaced against a
 * private one.
 *
 * `DATABASE_URL` remains the fallback for everywhere there is no binding:
 * migrations, scripts, tests and plain `next dev`.
 */
function connectionString(): string {
  const hyperdrive = tryBindings()?.HYPERDRIVE?.connectionString;
  if (hyperdrive) return hyperdrive;

  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL environment variable is required");
  return url;
}

function createPrismaClient(): PrismaClient {
  return new PrismaClient({ adapter: new PrismaPg({ connectionString: connectionString() }) });
}

export function getPrisma(): PrismaClient {
  const store = requestScope.getStore();
  if (store) return (store.client ??= createPrismaClient());

  const ctx = getCloudflareContextOrNull()?.ctx;
  if (!ctx) return createPrismaClient();

  const existing = clientsByExecutionContext.get(ctx);
  if (existing) return existing;

  const client = createPrismaClient();
  clientsByExecutionContext.set(ctx, client);
  return client;
}

/**
 * Wrap a unit of work so every `prisma` access inside it shares one client, and
 * the client is disconnected when the work ends. Only the engine Worker's
 * entrypoint calls this, because it is the only entrypoint this repository
 * owns; the web Worker's boundary is the adapter context handled above.
 */
export async function withPrismaScope<T>(fn: () => Promise<T>): Promise<T> {
  const store: { client?: PrismaClient } = {};
  try {
    return await requestScope.run(store, fn);
  } finally {
    await store.client?.$disconnect().catch(() => {});
  }
}

export const prisma = new Proxy(
  // SAFETY: the target is never read. Every property access is intercepted by
  // the `get` trap below and served from the per-request client.
  {} as PrismaClient,
  {
    get(_target, prop, receiver) {
      return Reflect.get(getPrisma(), prop, receiver);
    },
  }
);
